name: Laravel-Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: ./api
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      working-directory: ./api
    - name: Generate key
      run: php artisan key:generate
      working-directory: ./api
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: ./api
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
      working-directory: ./api
    - name: artisan コマンドが正しく実行されるか
      run: |
        php artisan cache:clear
        php artisan config:cache
        php artisan route:clear
      working-directory: ./api
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
      working-directory: ./api
  
  deploy:
    
    if: github.ref == 'refs/heads/master'
    needs: [laravel-tests]
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.XSERVER_SSH_KEY }}
          USER_NAME: ${{ secrets.XSERVER_USER_NAME }}
          HOST_NAME: ${{ secrets.XSERVER_HOST_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -p 10022 -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} 'cd ~/safety-park.xyz/public_html/api/safety-park && git pull origin master && composer update && php artisan config:cache && php artisan route:cache && php artisan view:cache'
